apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: devops-repo-ssh-private-key
  namespace: argocd
spec:
  vault:
    name: bw-mmartin # name of key vault
    object:
      name: argocd-devops-repo-private-key # name of the akv object
      type: secret # akv object type
  output: 
    secret: 
      name: repo-creds # kubernetes secret name
      dataKey: sshPrivateKey # key to store object value in kubernetes secret