apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default
  source:
    path: argo-cd
    repoURL: git@github.com:mimartin12/gitops-qa-env.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true