apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - base/namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.1.3/manifests/install.yaml
  - base/argocd-secret-repoprivatekey.yaml
  - base/argocd-application.yaml

patchesStrategicMerge:
  - overlays/deployment.yaml
  - overlays/argocd-configmap.yaml
  - overlays/ssh-known-hosts-configmap.yaml