---

name: Deploy (QA)

on:
  workflow_dispatch:
    inputs:
      "tag":
        description: "Branch name to deploy (example: 'main')"
        required: true
        type: string
        default: main

permissions:
  pull-requests: write
  contents: write

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      SHA: ${{ steps.setup.outputs.tag }}
    steps:

      - name: Get branch commit
        id: setup
        run: |
          COMMIT=$(
            curl -s https://api.github.com/repos/${{ github.repository }}/commits?sha=${{ github.event.inputs.tag }} \
            | jq -r '.[0].sha'
          )
          echo "::set-output name=commit::${COMMIT:0:7}"

  pr:
    name: Deploy PR
    runs-on: ubuntu-latest
    needs:
      - setup
    env: 
      TAG: ${{ needs.setup.outputs.SHA }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create deploy Branch
        run: |
          git switch -c deploy/${{ env.TAG }}
          git push -u origin deploy/${{ env.TAG }}

      - name: Set image version
        working-directory: app/overlays/qa
        run: kustomize edit set image nginx=nginx:${{ env.TAG }} --stack-trace

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Update image version to ${{ env.TAG }}'

    
      - name: Create Version PR
        env:
          PR_BRANCH: "deploy/${{ env.TAG }}"
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          BASE_BRANCH: master
          TITLE: "Bump version to ${{ env.TAG }}"
        run: |
          gh pr create --title "$TITLE" \
            --base "$BASE" \
            --head "$PR_BRANCH" \
            --body "
              ## Type of change
              - [ ] Bug fix
              - [ ] New feature development
              - [ ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
              - [ ] Build/deploy pipeline (DevOps)
              - [X] Other
              ## Objective
              Automated version bump to ${{ env.TAG }}"


      - name: Find Pull Request
        uses: juliangruber/find-pull-request-action@v1
        id: find-pull-request
        with:
          branch: deploy/${{ env.TAG }}

      - name: Approve Pull Request
        uses: juliangruber/approve-pull-request-action@v1.1.1
        with:
          github-token: ${{ secrets.TOKEN }}
          number: ${{ steps.find-pull-request.outputs.number }}

      - name: Merge Pull Request
        uses: juliangruber/merge-pull-request-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.find-pull-request.outputs.number }}
          method: squash

    
