---

name: Deploy (QA)

on:
  workflow_dispatch:
    inputs:
      "tag":
        description: "Tag/Version to deploy"
        required: true
        type: string

permissions:
  pull-requests: write
  contents: write

jobs:
  pr:
    name: Deploy PR
    runs-on: ubuntu-latest
    env: 
      TAG: ${{ inputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create deploy Branch
        run: |
          git switch -c deploy/${{ env.TAG }}
          git push -u origin deploy/${{ env.TAG }}

      - name: Set image version
        working-directory: app/overlays/qa
        run: kustomize edit set image nginx=nginx:${{ env.TAG }} --stack-trace

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Update image version to ${{ env.TAG }}'

      - name: Create PR
        uses: peter-evans/create-pull-request@v3
        id: create-pr
        with:
          token: ${{ github.token }}
          commit-message: "Deploy ${{ env.TAG }}"
          title: "Deploy ${{ env.TAG }}"
          body: "Deploy ${{ env.TAG }}"
          branch: "deploy/${{ env.TAG }}"

    